# Form implementation generated from reading ui file 'tuvungqt6.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1338, 889)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(90, 100, 211, 81))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(90, 180, 211, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(90, 230, 211, 41))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(730, 120, 231, 41))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setGeometry(QtCore.QRect(730, 180, 261, 31))
        self.label_8.setObjectName("label_8")
        self.lnenhapfile = QtWidgets.QLineEdit(parent=Form)
        self.lnenhapfile.setGeometry(QtCore.QRect(510, 400, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lnenhapfile.setFont(font)
        self.lnenhapfile.setStyleSheet("QLineEdit {\n"
"   border: 1px solid black;\n"
"   border-radius: 8px;\n"
"   } \n"
"QLineEdit::focus{\n"
"   border-color: red;\n"
"}")
        self.lnenhapfile.setText("")
        self.lnenhapfile.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lnenhapfile.setObjectName("lnenhapfile")
        self.lnetienganh = QtWidgets.QLineEdit(parent=Form)
        self.lnetienganh.setGeometry(QtCore.QRect(510, 510, 371, 51))
        self.lnetienganh.setStyleSheet("QLineEdit {\n"
"   border: 1px solid black;\n"
"   border-radius: 8px;\n"
"   padding:5px;\n"
"   } \n"
"QLineEdit::focus{\n"
"   border-color: blue;\n"
"}\n"
"")
        self.lnetienganh.setObjectName("lnetienganh")
        self.lnetiengviet = QtWidgets.QLineEdit(parent=Form)
        self.lnetiengviet.setGeometry(QtCore.QRect(510, 600, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lnetiengviet.setFont(font)
        self.lnetiengviet.setStyleSheet("QLineEdit {\n"
"   border: 1px solid black;\n"
"   border-radius: 8px;\n"
"   } \n"
"QLineEdit::focus{\n"
"   border-color: red;\n"
"}\n"
"")
        self.lnetiengviet.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lnetiengviet.setObjectName("lnetiengviet")
        self.label_14 = QtWidgets.QLabel(parent=Form)
        self.label_14.setGeometry(QtCore.QRect(350, 500, 111, 71))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=Form)
        self.label_15.setGeometry(QtCore.QRect(350, 600, 171, 51))
        self.label_15.setObjectName("label_15")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(350, 760, 171, 61))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.btnsubmit = QtWidgets.QPushButton(parent=Form)
        self.btnsubmit.setGeometry(QtCore.QRect(940, 530, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btnsubmit.setFont(font)
        self.btnsubmit.setStyleSheet("QPushButton{\n"
"   border: 1px solid black;\n"
"   border-radius: 14px;\n"
"   padding:2px;\n"
"   color:white;\n"
"   background:rgb(32, 3, 255);\n"
"   } \n"
"QPushButton::focus{\n"
"   border-color: blue;\n"
"}")
        self.btnsubmit.setObjectName("btnsubmit")
        self.txtloikhuyen = QtWidgets.QTextEdit(parent=Form)
        self.txtloikhuyen.setGeometry(QtCore.QRect(520, 740, 361, 91))
        self.txtloikhuyen.setStyleSheet("QTextEdit {\n"
"   border: 1px solid black;\n"
"   border-radius: 8px;\n"
"   } \n"
"QTextEdit::focus{\n"
"   border-color: red;\n"
"}")
        self.txtloikhuyen.setObjectName("txtloikhuyen")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(330, 180, 281, 41))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"   border: 1px solid black;\n"
"   border-radius: 8px;\n"
"   padding:5px;\n"
"   } \n"
"QLineEdit::focus{\n"
"   border-color: blue;\n"
"}\n"
"")
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.btnbatdauhoc = QtWidgets.QPushButton(parent=Form)
        self.btnbatdauhoc.setGeometry(QtCore.QRect(510, 450, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnbatdauhoc.setFont(font)
        self.btnbatdauhoc.setStyleSheet("QPushButton{\n"
"   border: 1px solid black;\n"
"   border-radius: 14px;\n"
"   padding:2px;\n"
"   color:white;\n"
"   background:rgb(32, 3, 255);\n"
"   } \n"
"QPushButton::focus{\n"
"   border-color: blue;\n"
"}")
        self.btnbatdauhoc.setObjectName("btnbatdauhoc")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 120, 281, 41))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"   border: 1px solid black;\n"
"   border-radius: 8px;\n"
"   padding:5px;\n"
"   } \n"
"QLineEdit::focus{\n"
"   border-color: blue;\n"
"}\n"
"")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(330, 230, 281, 41))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"   border: 1px solid black;\n"
"   border-radius: 8px;\n"
"   padding:5px;\n"
"   } \n"
"QLineEdit::focus{\n"
"   border-color: blue;\n"
"}\n"
"")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_10 = QtWidgets.QLabel(parent=Form)
        self.label_10.setGeometry(QtCore.QRect(730, 230, 241, 31))
        self.label_10.setObjectName("label_10")
        self.progress_tiledungsai = QtWidgets.QProgressBar(parent=Form)
        self.progress_tiledungsai.setGeometry(QtCore.QRect(520, 682, 361, 31))
        self.progress_tiledungsai.setProperty("value", 0)
        self.progress_tiledungsai.setObjectName("progress_tiledungsai")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(350, 680, 151, 31))
        self.label_5.setObjectName("label_5")
        self.btn_hoclai = QtWidgets.QPushButton(parent=Form)
        self.btn_hoclai.setGeometry(QtCore.QRect(710, 450, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_hoclai.setFont(font)
        self.btn_hoclai.setStyleSheet("QPushButton{\n"
"   border: 1px solid black;\n"
"   border-radius: 14px;\n"
"   padding:2px;\n"
"   color:white;\n"
"   background:rgb(32, 3, 255);\n"
"   } \n"
"QPushButton::focus{\n"
"   border-color: blue;\n"
"}")
        self.btn_hoclai.setObjectName("btn_hoclai")
        self.lnenhapfile_2 = QtWidgets.QLineEdit(parent=Form)
        self.lnenhapfile_2.setGeometry(QtCore.QRect(300, 30, 771, 51))
        self.lnenhapfile_2.setStyleSheet("QLineEdit {\n"
"   border: 1px solid black;\n"
"   border-radius: 8px;\n"
"   padding:5px;\n"
"   } \n"
"QLineEdit::focus{\n"
"   border-color: blue;\n"
"}")
        self.lnenhapfile_2.setObjectName("lnenhapfile_2")
        self.label_12 = QtWidgets.QLabel(parent=Form)
        self.label_12.setGeometry(QtCore.QRect(500, 20, 611, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lnenhapfile_3 = QtWidgets.QLineEdit(parent=Form)
        self.lnenhapfile_3.setGeometry(QtCore.QRect(60, 100, 1231, 251))
        self.lnenhapfile_3.setStyleSheet("QLineEdit {\n"
"   border: 1px solid black;\n"
"   border-radius: 8px;\n"
"   padding:5px;\n"
"   } \n"
"QLineEdit::focus{\n"
"   border-color: blue;\n"
"}")
        self.lnenhapfile_3.setObjectName("lnenhapfile_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(990, 120, 261, 41))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"   border: 1px solid black;\n"
"   border-radius: 8px;\n"
"   padding:5px;\n"
"   } \n"
"QLineEdit::focus{\n"
"   border-color: blue;\n"
"}\n"
"")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(990, 170, 261, 41))
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"   border: 1px solid black;\n"
"   border-radius: 8px;\n"
"   padding:5px;\n"
"   } \n"
"QLineEdit::focus{\n"
"   border-color: blue;\n"
"}\n"
"")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(990, 230, 261, 41))
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"   border: 1px solid black;\n"
"   border-radius: 8px;\n"
"   padding:5px;\n"
"   } \n"
"QLineEdit::focus{\n"
"   border-color: blue;\n"
"}\n"
"")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lnenhapfile_4 = QtWidgets.QLineEdit(parent=Form)
        self.lnenhapfile_4.setGeometry(QtCore.QRect(60, 380, 1231, 461))
        self.lnenhapfile_4.setStyleSheet("QLineEdit {\n"
"   border: 1px solid black;\n"
"   border-radius: 8px;\n"
"   padding:5px;\n"
"   } \n"
"QLineEdit::focus{\n"
"   border-color: blue;\n"
"}")
        self.lnenhapfile_4.setObjectName("lnenhapfile_4")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(90, 290, 231, 31))
        self.label_6.setObjectName("label_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(330, 290, 281, 41))
        self.lineEdit_7.setStyleSheet("QLineEdit {\n"
"   border: 1px solid black;\n"
"   border-radius: 8px;\n"
"   padding:5px;\n"
"   } \n"
"QLineEdit::focus{\n"
"   border-color: blue;\n"
"}\n"
"")
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(730, 290, 211, 31))
        self.label_9.setObjectName("label_9")
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(990, 290, 261, 41))
        self.lineEdit_8.setStyleSheet("QLineEdit {\n"
"   border: 1px solid black;\n"
"   border-radius: 8px;\n"
"   padding:5px;\n"
"   } \n"
"QLineEdit::focus{\n"
"   border-color: blue;\n"
"}\n"
"")
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lnenhapfile_4.raise_()
        self.lnenhapfile_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.lnenhapfile.raise_()
        self.lnetienganh.raise_()
        self.lnetiengviet.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_4.raise_()
        self.btnsubmit.raise_()
        self.txtloikhuyen.raise_()
        self.lineEdit.raise_()
        self.btnbatdauhoc.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.label_10.raise_()
        self.progress_tiledungsai.raise_()
        self.label_5.raise_()
        self.btn_hoclai.raise_()
        self.lnenhapfile_2.raise_()
        self.label_12.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_6.raise_()
        self.label_6.raise_()
        self.lineEdit_7.raise_()
        self.label_9.raise_()
        self.lineEdit_8.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Gói từ vựng Ngoại lệ trong python:"))
        self.label_2.setText(_translate("Form", "Gói từ vựng gia đình :"))
        self.label_3.setText(_translate("Form", "Gói từ vựng Python:"))
        self.label_7.setText(_translate("Form", "Gói từ vựng động vật:"))
        self.label_8.setText(_translate("Form", "Gói từ vựng môi trường :"))
        self.lnenhapfile.setPlaceholderText(_translate("Form", "Nhập gói từ vựng bạn muốn học:"))
        self.lnetiengviet.setPlaceholderText(_translate("Form", "Nhập đáp án của bạn"))
        self.label_14.setText(_translate("Form", "Tiếng Anh:"))
        self.label_15.setText(_translate("Form", "Tiếng Việt:"))
        self.label_4.setText(_translate("Form", "Phản hồi:"))
        self.btnsubmit.setText(_translate("Form", "Kiểm tra và học tiếp"))
        self.lineEdit.setText(_translate("Form", "family.xlsx"))
        self.btnbatdauhoc.setText(_translate("Form", "Bắt đầu học"))
        self.lineEdit_2.setText(_translate("Form", "ngoailetrongpython.xlsx"))
        self.lineEdit_3.setText(_translate("Form", "python.xlsx"))
        self.label_10.setText(_translate("Form", "Gói từ vựng nghề nghiệp:"))
        self.label_5.setText(_translate("Form", "Tỉ lệ đúng :"))
        self.btn_hoclai.setText(_translate("Form", "Ôn lại từ sai"))
        self.label_12.setText(_translate("Form", "ỨNG DỤNG HỌC TIẾNG ANH CƠ BẢN"))
        self.lineEdit_4.setText(_translate("Form", "vocabdongvat.xlsx"))
        self.lineEdit_5.setText(_translate("Form", "vocabmoitruong.xlsx"))
        self.lineEdit_6.setText(_translate("Form", "vocabnghenghiep.xlsx"))
        self.label_6.setText(_translate("Form", "Gói từ vựng trường học :"))
        self.lineEdit_7.setText(_translate("Form", "vocabtruonghoc.xlsx"))
        self.label_9.setText(_translate("Form", "Gói từ vựng tính cách :"))
        self.lineEdit_8.setText(_translate("Form", "vocabtinhcach.xlsx"))
